function [param_names,SSnms,sp_cols,time_names] = get_naming_terms()
    time_names = {'Mid-therapy', 'Therapy cessation','1wk post',...
    '2wk post','1mo post','3mo post','6mo post','12mo post'};

    SSnms = {'nAB Dominated','Li Dominated','oLB Dominated','P Dominated'};

    param_names = {'k_{grow}-nAB','k_{grow}-Li','k_{grow}-oLB',...
    'k_{grow}-P','\alpha_{nAB->nAB}','\alpha_{nAB->Li}',...
    '\alpha_{nAB->oLB}','\alpha_{nAB->P}','\alpha_{Li->nAB}',...
    '\alpha_{Li->Li}','\alpha_{Li->oLB}','\alpha_{Li->P}',...
    '\alpha_{oLB->nAB}','\alpha_{oLB->Li}','\alpha_{oLB->oLB}',...
    '\alpha_{oLB->P}','\alpha_{P->nAB}','\alpha_{P->Li}',...
    '\alpha_{P->oLB}','\alpha_{P->P}'};

       sp_cols = [0.9290 0.6940 0.1250; 
        0.5 0.5 0.5; 
        0.3010 0.7450 0.9330;
        0.2941 0 0.5098];
end